---
- name: Actualizar cache de paquetes (apt)
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Instalar Apache
  ansible.builtin.package:
    name: "{{ apache_package }}"
    state: present
    update_cache: true
  become: true

- name: Copiar configuración de Apache para WordPress
  ansible.builtin.template:
    src: wordpress.conf.j2
    dest: "{{ apache_path }}wordpress.conf"
    mode: '0644'
  notify: Reiniciar Apache

- name: Verificar si mod_rewrite está habilitado
  ansible.builtin.command: a2query -m rewrite
  register: mod_rewrite_enabled
  failed_when: false
  changed_when: false

- name: Asegurarse de que mod_rewrite esté habilitado
  ansible.builtin.command: a2enmod rewrite
  when: ansible_os_family == "Debian" and mod_rewrite_enabled.rc != 0
  changed_when: true
  notify: Reiniciar Apache

- name: Verificar si el sitio por defecto está habilitado
  ansible.builtin.command: a2query -s 000-default
  register: default_site_enabled
  failed_when: false
  changed_when: false

- name: Deshabilitar sitio por defecto
  ansible.builtin.command: a2dissite 000-default.conf
  when: ansible_os_family == "Debian" and default_site_enabled.rc == 0
  notify: Reiniciar Apache
  changed_when: true
